### ISSUE TITLE
repository mojolicious-plugin-soap-server missing

### ISSUE THREAD

**Issue by eserte** [oposs/mojo-soap-client#5]
Sorry for using this issue tracker for a problem with Mojolicious-Plugin-SOAP-Server --- but that module does not have a valid issue tracker. The MetaCPAN issues link points to https://github.com/oetiker/mojolicious-plugin-soap-server/issues which responds with a 404 page.

**Comment by oetiker** [comment]
fixed :) in mojolicious-plugin-soap-server 0.1.4
